# Generated by Django 4.1.6 on 2023-03-03 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nmscdcl_auth', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='api_hits',
            field=models.IntegerField(default=0),
        ),
    ]
