# Generated by Django 4.1.6 on 2023-03-02 08:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('nmscdcl_services', '0006_alter_datastore_connection_params'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShapeFiles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('folder_name', models.CharField(blank=True, max_length=255, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shape_files', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
