# Generated by Django 4.1.6 on 2023-03-03 13:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nmscdcl_services', '0008_apihit'),
    ]

    operations = [
        migrations.RenameField(
            model_name='apihit',
            old_name='api_hits',
            new_name='count',
        ),
    ]
